// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewWindow():Promise<void>;

export function GetCountdownDuration():Promise<number|number>;

export function GetCurrentMode():Promise<string>;

export function ResetTimer():Promise<void>;

export function SetCountdownDuration(arg1:number,arg2:number):Promise<void>;

export function StartTimer():Promise<void>;

export function StopTimer():Promise<void>;

export function SwitchToCountdownMode():Promise<void>;

export function SwitchToTimeMode():Promise<void>;
