// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewWindow() {
  return window['go']['main']['App']['CreateNewWindow']();
}

export function GetCountdownDuration() {
  return window['go']['main']['App']['GetCountdownDuration']();
}

export function GetCurrentMode() {
  return window['go']['main']['App']['GetCurrentMode']();
}

export function ResetTimer() {
  return window['go']['main']['App']['ResetTimer']();
}

export function SetCountdownDuration(arg1, arg2) {
  return window['go']['main']['App']['SetCountdownDuration'](arg1, arg2);
}

export function StartTimer() {
  return window['go']['main']['App']['StartTimer']();
}

export function StopTimer() {
  return window['go']['main']['App']['StopTimer']();
}

export function SwitchToCountdownMode() {
  return window['go']['main']['App']['SwitchToCountdownMode']();
}

export function SwitchToTimeMode() {
  return window['go']['main']['App']['SwitchToTimeMode']();
}
